version: 2
jobs:
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run: cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"